### ISSUE TITLE
unconnected edge annotations disappear

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#387] opened 2017-09-24 14:41 UTC
In the test file https://gist.github.com/andrewschultz/cba89dff0b0b721163bbe8d517e9f445 we have 3 connectors--the middle one shows s, m and e for start, middle and end text. But if we detach the connector, we see only the s, or nothing at all.

**Comment by Nyun0** [comment] 2018-11-08 21:43
I can confirm this - in #456 you can see that is the case on the bottom-right corner (map saved in v1.2.1 and opened in v1.7.1)
![text_wrapping](https://user-images.githubusercontent.com/44881234/48228711-45cded80-e3a6-11e8-89fd-566d5d168ed7.png)

**Comment by Nyun0** [comment] 2018-11-14 14:07
The reason for this is because the vertex of the unattached end of the line has no port assigned, resulting in NPE. The fix is easy, working on it.

**Comment by Nyun0** [comment] 2018-11-14 14:15
@andrewschultz, can you check out my branch [start-end-copy](https://github.com/Nyun0/trizbort/commits/start-end-copy) if that resolves the issue? [f7dbb9f](https://github.com/Nyun0/trizbort/commit/45fee6c1ca40ac4ab7d226935e767bf361e45045)

**Comment by Nyun0** [comment] 2018-11-19 14:40
@JasonLautzenheiser, I think this one can be closed.

**Comment by JasonLautzenheiser** [comment] 2020-08-15 13:25
This was fixed long ago, but for some reason I never closed this issue.

**Closed by JasonLautzenheiser** 2020-08-15 13:25 UTC
Labels: no-issue-activity
