### ISSUE TITLE
Line color change doesn't persist without trickery

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#95] opened 2015-08-14 00:23 UTC
The default line color is blue. But if we change the default line color to black, then create a new connection, that connection is blue. We must highlight it and type P to change it to black.

I think this is regressive from 1.5.8.* but I'm not sure.

The workaround is to highlight everything and type P, but that'd (temporarily) undo any dotted or one-way lines. I can also edit the XML file so color 0000ff vanishes, so this is not too critical a bug with 2 workarounds.

**Comment by JasonLautzenheiser** [comment] 2015-09-05 15:34
Duplicate of #104

**Closed by JasonLautzenheiser** 2015-09-05 15:34 UTC
