### ISSUE TITLE
Error on initial saving of map.

### ISSUE THREAD

**Issue by TheDarchy** [JasonLautzenheiser/trizbort#427] opened 2018-04-02 03:26 UTC
This error has appeared from version 1.6.0 - When saving a map for the first time.

"There was a problem saving the map: The path is not of a legal form."

**Comment by JasonLautzenheiser** [comment] 2018-04-07 12:47
Was having some computer issues, so wasn't able to to look at this.   Hoping to check it out this weekend.

**Comment by JasonLautzenheiser** [comment] 2018-04-07 18:34
I can reproduce this in versions 1.6 and 1.6.1, but I can't reproduce it in the current unreleased code.  This should be fixed then in the upcoming release.

I will expedite the release

**Comment by JasonLautzenheiser** [comment] 2018-04-07 18:40
I should note also, in my testing it appears the file is actually being saved, the error comes after the file is saved despite the misleading error message.

**Comment by TheDarchy** [comment] 2018-04-09 06:36
That's great news thank you for taking the time to update.

**Closed** 2018-04-18 00:31 UTC
Labels: bug
