### ISSUE TITLE
Support export map to Choicescript

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#272] opened 2016-04-30 11:25 UTC
While this seems very doable, I think we'll have to add some properties to connections to make it more meaningful.  

For example, direction's really don't have to matter in these type of games....so connections are less about connecting two rooms in a direction and more about a path between two selections.

So for connections, I could see putting a description or label on them to indicate the link text that the choice displays to link to that "room".  But we need to consider, how does that text play into say standard parser languages?

**Comment by JasonLautzenheiser** [comment] 2016-04-30 11:30
I guess the question is also...does it even make sense to export trizbort maps to choicescript or languages of those types?

**Comment by andrewschultz** [comment] 2016-05-01 02:00
I like this idea, but the problem is that Twine already has a sort of export. And there would be a lot of one-way arrows. As I'd see it you'd have a starting room and then any passage would have something in the middle indicating the choice. This would need to be done repeatedly, and it'd be a bit awkward. It'd be a cool experiment, but I don't know about the practical value for development.

This would probably necessitate a flag for custom arrow creation so that the user would be able to fill in the option. I'll post something to my gist in a bit.

However, in terms of bridging the gap between the parser and choice communities, this would be something really cool to do.

**Comment by JasonLautzenheiser** [comment] 2016-05-01 12:17
I know very little about the choice tools and what their capabilities are, but it would be interesting to fill that gap if there are any.

Another thought I had, which I'm sure would be much more difficult and prone to issues, would be to go the opposite way of the export....in other words, what if we could read source and build a map from it.

This I know would be a massive undertaking I think, but wouldn't it be cool to load up your favorite I7 source code and have it happily build a map for you.  

Is it worth the effort?  Perhaps not, as building even a basic parser, especially for something as complex as I7 is not a trivial project.  I could see perhaps some more structured languages might be a bit easier to do with...and of course a lot of tools already have something built in to generate the map from code, so perhaps not worth it.....but admit it....it would be cool to get that working!

**Comment by andrewschultz** [comment] 2016-05-01 20:52
I agree. But there is so much else to do! I do think it might be possible to read choicescript into a map.

I think the Inform IDE already sort of does it with "index map with," but--yeah, it'd be great to have a Trizbort map, and it might not be hard to read in something crudely, and if there's a big contradiction, we just bail at the line where it happens.

Perhaps we could even do things like specify room size in the comments.

But first things first: just getting the map to work. I actually don't think it'd be that bad, if we do a bit of parsing. We'd have to start small, but I have plenty of complex test cases for when it grows.

**Comment by JasonLautzenheiser** [comment] 2016-05-01 21:03
The more I think about it, I think I may create a new project, a Trizbort companion project that I can play with this in.  If it ever gains momentum, then we could always include it back in to the main project.  But really we're just talking about writing a parsing engine (for different languages) outputting to a Trizbort file.  Start small with it and then build upon if it warrants it.  But keep this project (Trizbort) free from it for now.

**Comment by andrewschultz** [comment] 2016-05-01 21:39
Well, definitely let me know if/when that happens. I like the idea of a separate project that can be merged. Now you mention it, I could do it in perl, I think. Or give it a try. But it would be much harder to fold back into Trizbort, of course.

**Closed** 2016-08-13 02:23 UTC
Labels: Dead, question
