### ISSUE TITLE
Exception on zooming - hard to reproduce

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#177] opened 2015-09-27 03:51 UTC
![zoom-error](https://cloud.githubusercontent.com/assets/6201356/10120986/7c5675d4-649c-11e5-9b56-dc9f1911bcb3.png)

I'm not sure how to reproduce this reliably, but it does happen, and I hope the error message helps.

This happened just after I zoomed in from 62% to 100%. Maybe the variable names will help. I had been tinkering with room borders before. I made the one room's all white.

Maybe looking at the code will point out a possible bound being overstepped.

Best guess is UpdateScrollBars in canvas.cs.

I'd also guess it happens when a horizontal or vertical scrollbar is (de)activated.

**Comment by JasonLautzenheiser** [comment] 2015-09-27 14:25
Interesting......on a side note.  I tested MTW's game early on in the development and I used the auto-mapper and his game helped me find quite a few bugs.....how's the automapper working for you with his game?  It originally had issues dealing with rooms with similar names e.g. Trees (near small waterfall) and Trees (deep in woods)

**Comment by andrewschultz** [comment] 2015-09-27 21:05
I didn't use the automapper--figured I'd do everything manually.

I'd be curious to see how it worked on my game, actually. Now you mention it, Marshal's is a rather good test case.

**Comment by andrewschultz** [comment] 2015-09-27 21:13
To add...I noticed a small bug with my game if I used the IDE debugging. I don't know how valid or prevalent it is, though. I'll report it separately.

**Comment by JasonLautzenheiser** [comment] 2016-05-05 02:08
Can't reproduce so closing for now.

**Closed by JasonLautzenheiser** 2016-05-05 02:08 UTC
